spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Educacional1983
logging:
  level:
    org.springframework.boot.devtools.restart.Restarter: OFF
